name: Build

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test the Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      # Test
      - name: Run unit tests
        #run: dotnet test --no-restore --results-directory ./testresults/ --logger:trx
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory testresults
      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: testresults/*.trx # Path to test results
          reporter: dotnet-trx
      # Code coverage
      - name: Copy coverage to predictable location
        run: cp testresults/**/coverage.cobertura.xml coverage.cobertura.xml
      - name: Generate code coverage report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          badge: true
          fail_below_min: true
          filename: coverage.cobertura.xml
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "0 0" # Line and branch threshold percentages
      - name: Add coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        # if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      # Lint
      - name: Lint Code Base
        uses: github/super-linter@v4.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          #DISABLE_ERRORS: true # This may be needed if linting becomes a pain
          OUTPUT_DETAILS: detailed
          OUTPUT_FORMAT: tap
          VALIDATE_CSHARP: true # Only validate C#, this will prevent validating all the other languages by default
          VALIDATE_ALL_CODEBASE: true # Lint entire codebase rather than just the changes
      - name: Upload lint report as an artifact
        uses: actions/upload-artifact@master
        with:
          name: linter-report
          path: "${{ github.workspace }}/super-linter.report/"
