name: Build

on:
  push:
    #branches: [master]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test the Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      # Test
      - name: Run unit tests
        #run: dotnet test --no-restore --results-directory ./testresults/ --logger:trx
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory testresults
      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: testresults/*.trx # Path to test results
          reporter: dotnet-trx
      # Code coverage
      - name: Copy coverage to predictable location
        run: cp testresults/**/coverage.cobertura.xml coverage.cobertura.xml
      - name: Generate code coverage report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          badge: true
          fail_below_min: true
          filename: coverage.cobertura.xml
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "0 0" # Line and branch threshold percentages
      - name: Add coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        # if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      # Lint
      - name: Lint Code Base
        uses: github/super-linter@v4.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          #DISABLE_ERRORS: true # This may be needed if linting becomes a pain
          OUTPUT_DETAILS: detailed
          OUTPUT_FORMAT: tap
          VALIDATE_CSHARP: true # Only validate C#, this will prevent validating all the other languages by default
          VALIDATE_ALL_CODEBASE: true # Lint entire codebase rather than just the changes
      - name: Upload lint report as an artifact
        uses: actions/upload-artifact@master
        with:
          name: linter-report
          path: "${{ github.workspace }}/super-linter.report/"
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.9
        with:
          reports: "coverage.cobertura.xml" # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
          targetdir: "coveragereport" # REQUIRED # The directory where the generated report should be saved.
          reporttypes: "HtmlInline;Cobertura" # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, Html_Dark, Html_Light, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlInline_AzurePipelines_Light, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MarkdownSummary, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary
          assemblyfilters: "+*" # Optional list of assemblies that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
          classfilters: "+*" # Optional list of classes that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
          filefilters: "+*" # Optional list of files that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
          verbosity: "Info" # The verbosity level of the log messages. Values: Verbose, Info, Warning, Error, Off
          title: "Coverage report" # Optional title.
          tag: "${{ github.run_number }}_${{ github.run_id }}" # Optional tag or build version.
          toolpath: "reportgeneratortool" # Default directory for installing the dotnet tool.
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: CoverageReport # Artifact name
          path: coveragereport # Directory containing files to upload
